# Generated by Django 4.1.3 on 2022-11-16 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spiderdetail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='spiderdetail.config'),
        ),
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
